[package]
authors = ["Konstantin Gukov <gukkos@gmail.com>"]
name = "python-dtparse"
version = "1.0.0"

[dependencies]
pyo3 = "0.2.6"
chrono = "0.4"

[lib]
name = "dtparse"
crate-type = ["cdylib"]

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3

[profile.test]
opt-level = 3
